# -*- coding: utf-8 -*-
"""slangClass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bmt-OfAJwAAfjnWIdwCqXZlvI7TvF1Xv
"""

class slang:
  import requests

  # Replace 'path_to_slang_file' with the actual file path
  file_path = 'slang.txt'

  # Read the slang data from the local file
  with open(file_path, 'r', encoding='utf-8') as file:
    slang_data = file.read()

  # Process the slang data and create a dictionary
  slang_dict = {}
  for line in slang_data.split('\n'):
      line = line.strip()
      if line:
          parts = line.split('=')
          abbreviation = parts[0].strip()
          full_form = parts[1].strip() if len(parts) > 1 else ""  # Handle lines with no full form
          slang_dict[abbreviation] = full_form
  def slang_res(self,input):
    res = ""
    for w in input.split():
      res = res + self.slang_dict.get(w.upper(),w).lower() + " "
    return res.strip()